apiVersion: apps/v1
kind: Deployment
metadata:
  name: x402-tip-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x402-tip-app
  template:
    metadata:
      labels:
        app: x402-tip-app
    spec:
      containers:
      - name: x402-tip-app
        image: devmiguelavelar/x402-tip-app
        ports:
        - containerPort: 3000